# Generated by Django 5.2.5 on 2025-09-09 19:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Expense', 'Expense')], max_length=100)),
                ('item_service', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Airtime/Data', 'Airtime/Data'), ('Utilities', 'Utilities (Bills)'), ('Gifts/Donations', 'Gifts/Donations'), ('Personal', 'Personal (Haircut, Gym, etc)'), ('Household', 'Household items/supplies'), ('Entertainment', 'Entertainment (Alcohol, club, etc)'), ('Clothing', 'Clothing'), ('Education', 'Education'), ('Medical', 'Medical/Healthcare'), ('Child Care/Family', 'ChildCare/Family Support'), ('Housing', 'Housing'), ('Car Repair', 'Car Repair/Maintenance'), ('Savings/Investment', 'Savings/Investment'), ('Emergency/Unexpected', 'Emergency/Unexpected')], max_length=100)),
                ('amount', models.PositiveSmallIntegerField()),
                ('note', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
