# Generated by Django 5.2.5 on 2025-09-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Airtime/Data', 'Airtime/Data'), ('Utilities', 'Utilities (Bills)'), ('Gifts/Donations', 'Gifts/Donations'), ('Personal', 'Personal (Haircut, Gym, etc)'), ('Household', 'Household items/supplies'), ('Entertainment', 'Entertainment (Alcohol, club, etc)'), ('Clothing', 'Clothing'), ('Education', 'Education'), ('Medical', 'Medical/Healthcare'), ('Child Care/Family', 'ChildCare/Family Support'), ('Housing', 'Housing'), ('Car Repair', 'Car Repair/Maintenance'), ('Savings/Investment', 'Savings/Investment'), ('Emergency/Unexpected', 'Emergency/Unexpected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
