# Generated by Django 5.2.5 on 2025-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_expense_category_alter_expense_item_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('airtime/Data', 'Airtime/Data'), ('utilities', 'Utilities (Bills)'), ('gifts/Donations', 'Gifts/Donations'), ('personal', 'Personal (Haircut, Gym, etc)'), ('household', 'Household items/supplies'), ('entertainment', 'Entertainment (Alcohol, club, etc)'), ('clothing', 'Clothing'), ('education', 'Education'), ('vacation', 'Vacation'), ('medical', 'Medical/Healthcare'), ('child Care/Family', 'ChildCare/Family Support'), ('housing', 'Housing'), ('car repair', 'Car Repair/Maintenance'), ('savings/Investment', 'Savings/Investment'), ('emergency/unexpected', 'Emergency/Unexpected')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item_service',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
