# Generated by Django 5.2.5 on 2025-09-12 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_expense_category_alter_expense_item_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('airtime/Data', 'Airtime/Data'), ('utilities', 'Utilities (Bills)'), ('Family (Parents, Siblings, etc)', 'Family(Parents, Siblings etc)'), ('gifts/Donations', 'Gifts/Donations'), ('personal', 'Personal (Haircut, Gym, etc)'), ('household', 'Household items/supplies'), ('entertainment', 'Entertainment (Alcohol, club, etc)'), ('clothing', 'Clothing'), ('education', 'Education'), ('vacation', 'Vacation'), ('medical', 'Medical/Healthcare'), ('child Care/Family', 'ChildCare/Family Support'), ('housing', 'Housing'), ('car repair', 'Car Repair/Maintenance'), ('savings/Investment', 'Savings/Investment'), ('emergency/unexpected', 'Emergency/Unexpected')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=100)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Not Started', max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
