# Generated by Django 5.2.5 on 2025-09-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_ideas_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='detail',
            new_name='objective',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries (raw food: rice, yam, meat, tomatoes, fruits, etc.'), ('eating_out', 'Eating Out / Restaurants'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('airtime/Data', 'Airtime/Data'), ('utilities', 'Utilities (Bills)'), ('Family (Parents, Siblings, etc)', 'Family(Parents, Siblings etc)'), ('gifts/Donations', 'Gifts/Donations'), ('personal', 'Personal (Haircut, Gym, etc)'), ('household', 'Household items/supplies'), ('entertainment', 'Entertainment (Alcohol, club, etc)'), ('spouse', 'Spouse'), ('girlfriend/boyfriend', 'Girlfriend/Boyfriend'), ('clothing', 'Clothing'), ('education', 'Education'), ('vacation', 'Vacation'), ('medical', 'Medical/Healthcare'), ('child Care/Family', 'ChildCare/Family Support'), ('housing', 'Housing'), ('car repair', 'Car Repair/Maintenance'), ('savings/Investment', 'Savings/Investment'), ('emergency/unexpected', 'Emergency/Unexpected'), ('miscellaneous', 'Miscellaneous')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='myapp.idea')),
            ],
        ),
    ]
