# Generated by Django 5.2.5 on 2025-09-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_detail_idea_objective_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='resource',
            new_name='text',
        ),
    ]
