# Generated by Django 5.2.5 on 2025-09-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_resource_requirement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('Business / Career', 'Business / Career'), ('Lifestyle / Personal Growth', 'Lifestyle / Personal Growth'), ('Education / Learning', 'Education / Learning'), ('Family / Relationships', 'Family / Relationships'), ('Intellectual / Creativity', 'Intellectual / Creativity'), ('Spirituality / Ethical', 'Spirituality / Ethical')], default='Business / Career', max_length=100),
        ),
    ]
