# Generated by Django 5.2.5 on 2025-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_idea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries (raw food: rice, yam, meat, tomatoes, fruits, etc.'), ('eat_out', 'Eating Out / Restaurants'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('airtime/Data', 'Airtime/Data'), ('utilities', 'Utilities (Bills)'), ('Extd Family', 'Family(Parents, Siblings etc)'), ('gifts/Donations', 'Gifts/Donations'), ('personal', 'Personal (Haircut, Gym, etc)'), ('household', 'Household items/supplies'), ('entertainment', 'Entertainment (Alcohol, club, etc)'), ('spouse', 'Spouse'), ('girl/boyfriend', 'Girlfriend/Boyfriend'), ('clothing', 'Clothing'), ('education', 'Education'), ('vacation', 'Vacation'), ('medical', 'Medical/Healthcare'), ('child care/family', 'ChildCare/Family Support'), ('housing', 'Housing'), ('car repair', 'Car Repair/Maintenance'), ('savings/Investment', 'Savings/Investment'), ('emergency/unexpected', 'Emergency/Unexpected'), ('miscellaneous', 'Miscellaneous')], default='', max_length=100),
        ),
    ]
